In [1]:
import dask.dataframe as dd
import dask.array as da
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv", nrows=1000)
df

,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0000028988387b115f69f31a3bf04f09,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1735.0,0,7.0,0,NaN,53447.0,...,36144.0,0,NaN,0.0,0,0,0.0,0.0,10.0,0
1,000007535c3f730efa9ea0b7ef1bd645,win8defender,1.1.14600.4,4.13.17134.1,1.263.48.0,0,7.0,0,NaN,53447.0,...,57858.0,0,NaN,0.0,0,0,0.0,0.0,8.0,0
2,000007905a28d863f6d0d597892cd692,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1341.0,0,7.0,0,NaN,53447.0,...,52682.0,0,NaN,0.0,0,0,0.0,0.0,3.0,0
3,00000b11598a75ea8ba1beea8459149f,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1527.0,0,7.0,0,NaN,53447.0,...,20050.0,0,NaN,0.0,0,0,0.0,0.0,3.0,1
4,000014a5f00daa18e76b81417eeb99fc,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1379.0,0,7.0,0,NaN,53447.0,...,19844.0,0,0.0,0.0,0,0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,00074c9f018c3e3d470115c70249c5da,win8defender,1.1.15100.1,4.18.1807.18075,1.273.920.0,0,7.0,0,NaN,47238.0,...,33133.0,1,NaN,0.0,1,1,0.0,0.0,10.0,0
996,00074d23b53a581a23006c0e0ae0dabc,win8defender,1.1.15200.1,4.18.1807.18075,1.275.497.0,0,7.0,0,NaN,47238.0,...,33115.0,1,NaN,0.0,0,0,0.0,0.0,11.0,0
997,00074e1776d7a11b01583b92ce9a22d1,win8defender,1.1.15200.1,4.18.1807.18075,1.275.568.0,0,7.0,0,NaN,53447.0,...,14746.0,0,NaN,0.0,0,0,0.0,0.0,7.0,1
998,000757f5602ee68e3419d3bfc4be808a,win8defender,1.1.15000.2,4.12.17007.18022,1.271.105.0,0,7.0,0,NaN,53447.0,...,64568.0,0,0.0,0.0,0,1,0.0,0.0,15.0,0
999,00075e5ef6378f1a3c7fda6941f896db,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1179.0,0,7.0,0,NaN,53447.0,...,28895.0,0,0.0,0.0,0,0,0.0,0.0,3.0,0

In [3]:
datatypes = df.dtypes.to_dict
datatypes

<bound method Series.to_dict of MachineIdentifier                           object
ProductName                                 object
EngineVersion                               object
AppVersion                                  object
AvSigVersion                                object
                                            ...
Census_IsPenCapable                          int64
Census_IsAlwaysOnAlwaysConnectedCapable    float64
Wdft_IsGamer                               float64
Wdft_RegionIdentifier                      float64
HasDetections                                int64
Length: 83, dtype: object>

In [4]:
datatypes = {'MachineIdentifier': 'O',
 'ProductName': 'O',
 'EngineVersion': 'O',
 'AppVersion': 'O',
 'AvSigVersion': 'O',
 'IsBeta': 'float32',
 'RtpStateBitfield': 'float32',
 'IsSxsPassiveMode': 'float32',
 'DefaultBrowsersIdentifier': 'float32',
 'AVProductStatesIdentifier': 'float32',
 'AVProductsInstalled': 'float32',
 'AVProductsEnabled': 'float32',
 'HasTpm': 'float32',
 'CountryIdentifier': 'float32',
 'CityIdentifier': 'float32',
 'OrganizationIdentifier': 'float32',
 'GeoNameIdentifier': 'float32',
 'LocaleEnglishNameIdentifier': 'float32',
 'Platform': 'O',
 'Processor': 'O',
 'OsVer': 'O',
 'OsBuild': 'float32',
 'OsSuite': 'float32',
 'OsPlatformSubRelease': 'O',
 'OsBuildLab': 'O',
 'SkuEdition': 'O',
 'IsProtected': 'float32',
 'AutoSampleOptIn': 'float32',
 'PuaMode': 'O',
 'SMode': 'float32',
 'IeVerIdentifier': 'float32',
 'SmartScreen': 'O',
 'Firewall': 'float32',
 'UacLuaenable': 'float32',
 'Census_MDC2FormFactor': 'O',
 'Census_DeviceFamily': 'O',
 'Census_OEMNameIdentifier': 'float32',
 'Census_OEMModelIdentifier': 'float32',
 'Census_ProcessorCoreCount': 'float32',
 'Census_ProcessorManufacturerIdentifier': 'float32',
 'Census_ProcessorModelIdentifier': 'float32',
 'Census_ProcessorClass': 'O',
 'Census_PrimaryDiskTotalCapacity': 'float32',
 'Census_PrimaryDiskTypeName': 'O',
 'Census_SystemVolumeTotalCapacity': 'float32',
 'Census_HasOpticalDiskDrive': 'float32',
 'Census_TotalPhysicalRAM': 'float32',
 'Census_ChassisTypeName': 'O',
 'Census_InternalPrimaryDiagonalDisplaySizeInInches': 'float32',
 'Census_InternalPrimaryDisplayResolutionHorizontal': 'float32',
 'Census_InternalPrimaryDisplayResolutionVertical': 'float32',
 'Census_PowerPlatformRoleName': 'O',
 'Census_InternalBatteryType': 'O',
 'Census_InternalBatteryNumberOfCharges': 'float32',
 'Census_OSVersion': 'O',
 'Census_OSArchitecture': 'O',
 'Census_OSBranch': 'O',
 'Census_OSBuildNumber': 'float32',
 'Census_OSBuildRevision': 'float32',
 'Census_OSEdition': 'O',
 'Census_OSSkuName': 'O',
 'Census_OSInstallTypeName': 'O',
 'Census_OSInstallLanguageIdentifier': 'float32',
 'Census_OSUILocaleIdentifier': 'float32',
 'Census_OSWUAutoUpdateOptionsName': 'O',
 'Census_IsPortableOperatingSystem': 'float32',
 'Census_GenuineStateName': 'O',
 'Census_IsFlightingInternal': 'float32',
 'Census_IsFlightsDisabled': 'float32',
 'Census_FlightRing': 'O',
 'Census_ThresholdOptIn': 'float32',
 'Census_FirmwareManufacturerIdentifier': 'float32',
 'Census_FirmwareVersionIdentifier': 'float32',
 'Census_IsSecureBootEnabled': 'float32',
 'Census_IsWIMBootEnabled': 'float32',
 'Census_IsVirtualDevice': 'float32',
 'Census_IsTouchEnabled': 'float32',
 'Census_IsPenCapable': 'float32',
 'Census_IsAlwaysOnAlwaysConnectedCapable': 'float32',
 'Wdft_IsGamer': 'float32',
 'Wdft_RegionIdentifier': 'float32',
 'HasDetections': 'uint8'}

In [5]:
df = dd.read_csv("train.csv", dtype=datatypes)
df

Dask DataFrame Structure:
               MachineIdentifier ProductName EngineVersion AppVersion AvSigVersion   IsBeta RtpStateBitfield IsSxsPassiveMode DefaultBrowsersIdentifier AVProductStatesIdentifier AVProductsInstalled AVProductsEnabled   HasTpm CountryIdentifier CityIdentifier OrganizationIdentifier GeoNameIdentifier LocaleEnglishNameIdentifier Platform Processor   OsVer  OsBuild  OsSuite OsPlatformSubRelease OsBuildLab SkuEdition IsProtected AutoSampleOptIn PuaMode    SMode IeVerIdentifier SmartScreen Firewall UacLuaenable Census_MDC2FormFactor Census_DeviceFamily Census_OEMNameIdentifier Census_OEMModelIdentifier Census_ProcessorCoreCount Census_ProcessorManufacturerIdentifier Census_ProcessorModelIdentifier Census_ProcessorClass Census_PrimaryDiskTotalCapacity Census_PrimaryDiskTypeName Census_SystemVolumeTotalCapacity Census_HasOpticalDiskDrive Census_TotalPhysicalRAM Census_ChassisTypeName Census_InternalPrimaryDiagonalDisplaySizeInInches Census_InternalPrimaryDisplayResolutionHorizontal Census_InternalPrimaryDisplayResolutionVertical Census_PowerPlatformRoleName Census_InternalBatteryType Census_InternalBatteryNumberOfCharges Census_OSVersion Census_OSArchitecture Census_OSBranch Census_OSBuildNumber Census_OSBuildRevision Census_OSEdition Census_OSSkuName Census_OSInstallTypeName Census_OSInstallLanguageIdentifier Census_OSUILocaleIdentifier Census_OSWUAutoUpdateOptionsName Census_IsPortableOperatingSystem Census_GenuineStateName Census_ActivationChannel Census_IsFlightingInternal Census_IsFlightsDisabled Census_FlightRing Census_ThresholdOptIn Census_FirmwareManufacturerIdentifier Census_FirmwareVersionIdentifier Census_IsSecureBootEnabled Census_IsWIMBootEnabled Census_IsVirtualDevice Census_IsTouchEnabled Census_IsPenCapable Census_IsAlwaysOnAlwaysConnectedCapable Wdft_IsGamer Wdft_RegionIdentifier HasDetections
npartitions=68
                          string      string        string     string       string  float32          float32          float32                   float32                   float32             float32           float32  float32           float32        float32                float32           float32                     float32   string    string  string  float32  float32               string     string     string     float32         float32  string  float32         float32      string  float32      float32                string              string                  float32                   float32                   float32                                float32                         float32                string                         float32                     string                          float32                    float32                 float32                 string                                           float32                                           float32                                         float32                       string                     string                               float32           string                string          string              float32                float32           string           string                   string                            float32                     float32                           string                          float32                  string                   string                    float32                  float32            string               float32                               float32                          float32                    float32                 float32                float32               float32             float32                                 float32      float32               float32         uint8
                             ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
...                          ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
                             ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
                             ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMapProjectable(755b8a7))

In [6]:
df

Dask DataFrame Structure:
               MachineIdentifier ProductName EngineVersion AppVersion AvSigVersion   IsBeta RtpStateBitfield IsSxsPassiveMode DefaultBrowsersIdentifier AVProductStatesIdentifier AVProductsInstalled AVProductsEnabled   HasTpm CountryIdentifier CityIdentifier OrganizationIdentifier GeoNameIdentifier LocaleEnglishNameIdentifier Platform Processor   OsVer  OsBuild  OsSuite OsPlatformSubRelease OsBuildLab SkuEdition IsProtected AutoSampleOptIn PuaMode    SMode IeVerIdentifier SmartScreen Firewall UacLuaenable Census_MDC2FormFactor Census_DeviceFamily Census_OEMNameIdentifier Census_OEMModelIdentifier Census_ProcessorCoreCount Census_ProcessorManufacturerIdentifier Census_ProcessorModelIdentifier Census_ProcessorClass Census_PrimaryDiskTotalCapacity Census_PrimaryDiskTypeName Census_SystemVolumeTotalCapacity Census_HasOpticalDiskDrive Census_TotalPhysicalRAM Census_ChassisTypeName Census_InternalPrimaryDiagonalDisplaySizeInInches Census_InternalPrimaryDisplayResolutionHorizontal Census_InternalPrimaryDisplayResolutionVertical Census_PowerPlatformRoleName Census_InternalBatteryType Census_InternalBatteryNumberOfCharges Census_OSVersion Census_OSArchitecture Census_OSBranch Census_OSBuildNumber Census_OSBuildRevision Census_OSEdition Census_OSSkuName Census_OSInstallTypeName Census_OSInstallLanguageIdentifier Census_OSUILocaleIdentifier Census_OSWUAutoUpdateOptionsName Census_IsPortableOperatingSystem Census_GenuineStateName Census_ActivationChannel Census_IsFlightingInternal Census_IsFlightsDisabled Census_FlightRing Census_ThresholdOptIn Census_FirmwareManufacturerIdentifier Census_FirmwareVersionIdentifier Census_IsSecureBootEnabled Census_IsWIMBootEnabled Census_IsVirtualDevice Census_IsTouchEnabled Census_IsPenCapable Census_IsAlwaysOnAlwaysConnectedCapable Wdft_IsGamer Wdft_RegionIdentifier HasDetections
npartitions=68
                          string      string        string     string       string  float32          float32          float32                   float32                   float32             float32           float32  float32           float32        float32                float32           float32                     float32   string    string  string  float32  float32               string     string     string     float32         float32  string  float32         float32      string  float32      float32                string              string                  float32                   float32                   float32                                float32                         float32                string                         float32                     string                          float32                    float32                 float32                 string                                           float32                                           float32                                         float32                       string                     string                               float32           string                string          string              float32                float32           string           string                   string                            float32                     float32                           string                          float32                  string                   string                    float32                  float32            string               float32                               float32                          float32                    float32                 float32                float32               float32             float32                                 float32      float32               float32         uint8
                             ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
...                          ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
                             ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
                             ...         ...           ...        ...          ...      ...              ...              ...                       ...                       ...                 ...               ...      ...               ...            ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...        ...         ...             ...     ...      ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                       ...                                    ...                             ...                   ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...              ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                              ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMapProjectable(755b8a7))

In [7]:
df.head(5)

,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0000028988387b115f69f31a3bf04f09,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1735.0,0.0,7.0,0.0,NaN,53447.0,...,36144.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,10.0,0
1,000007535c3f730efa9ea0b7ef1bd645,win8defender,1.1.14600.4,4.13.17134.1,1.263.48.0,0.0,7.0,0.0,NaN,53447.0,...,57858.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,8.0,0
2,000007905a28d863f6d0d597892cd692,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1341.0,0.0,7.0,0.0,NaN,53447.0,...,52682.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.0,0
3,00000b11598a75ea8ba1beea8459149f,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1527.0,0.0,7.0,0.0,NaN,53447.0,...,20050.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.0,1
4,000014a5f00daa18e76b81417eeb99fc,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1379.0,0.0,7.0,0.0,NaN,53447.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1

In [8]:
df.info()

<class 'dask.dataframe.dask_expr.DataFrame'>
Columns: 83 entries, MachineIdentifier to HasDetections
dtypes: float32(52), uint8(1), string(30)

In [9]:
df_sample = pd.read_csv("train.csv", nrows=100000, dtype=datatypes)

null_counts = df_sample.isnull().sum()

null_per = (null_counts / len(df_sample)) * 100
null_per.sort_values(ascending=False)

PuaMode                       99.969
Census_ProcessorClass         99.573
DefaultBrowsersIdentifier     95.110
Census_IsFlightingInternal    83.163
Census_InternalBatteryType    71.240
                               ...
Census_FlightRing              0.000
Census_IsSecureBootEnabled     0.000
Census_IsTouchEnabled          0.000
Census_IsPenCapable            0.000
HasDetections                  0.000
Length: 83, dtype: float64

In [10]:
df_sample

,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,DefaultBrowsersIdentifier,AVProductStatesIdentifier,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0000028988387b115f69f31a3bf04f09,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1735.0,0.0,7.0,0.0,NaN,53447.0,...,36144.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,10.0,0
1,000007535c3f730efa9ea0b7ef1bd645,win8defender,1.1.14600.4,4.13.17134.1,1.263.48.0,0.0,7.0,0.0,NaN,53447.0,...,57858.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,8.0,0
2,000007905a28d863f6d0d597892cd692,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1341.0,0.0,7.0,0.0,NaN,53447.0,...,52682.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.0,0
3,00000b11598a75ea8ba1beea8459149f,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1527.0,0.0,7.0,0.0,NaN,53447.0,...,20050.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,3.0,1
4,000014a5f00daa18e76b81417eeb99fc,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1379.0,0.0,7.0,0.0,NaN,53447.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,02e11f9b051950ba19ef87553f24b3d2,win8defender,1.1.15200.1,4.8.10240.17443,1.275.193.0,0.0,7.0,0.0,NaN,42086.0,...,12456.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0
99996,02e11ff750f98912e9073afe15bf5018,win8defender,1.1.15100.1,4.18.1806.18062,1.273.371.0,0.0,7.0,0.0,NaN,53447.0,...,43238.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,11.0,1
99997,02e120fd73a9b3981b80a879f1d94729,win8defender,1.1.15200.1,4.18.1807.18075,1.275.1244.0,0.0,7.0,0.0,NaN,7945.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0
99998,02e123408acf92064932e0900a42667b,win8defender,1.1.15200.1,4.18.1807.18075,1.275.1362.0,0.0,7.0,0.0,NaN,53447.0,...,52295.0,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0
99999,02e125f54e5e4aefc7a42cae452fe9b2,win8defender,1.1.15200.1,4.10.14393.1613,1.275.46.0,0.0,7.0,0.0,NaN,53447.0,...,31835.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0

PuaMode -> bu on off olan bir değer ve off'lar missing görünüyor.
UacLuaenable -> bu ya 1-3 ya da 45-48 almış ne ayak anlamadım yoksa outlier (?)
Census_ProcessorClass-> bu label verisi low mid high. burdaki %99 null da kesin yok anlamındadır
Census_PrimaryDiskTotalCapacity, Census_SystemVolumeTotalCapacity-> fena outlier

Census_HasOpticalDiskDrive, firewall, SMode, IsProtected, AutoSampleOptIn, IsSxsPassiveMode, IsBeta, Census_IsSecureBootEnabled-> boolean

Census_TotalPhysicalRAM-> bu da yüzbinlerde gezen veri.

Census_InternalBatteryType-> bu da bataryasız (desktop) olanlar için nan yazılmış

Census_InternalBatteryNumberOfCharges-> tam gradyan patlatmalık outlier. milyonluk outlierlar. 

Census_IsFlightsDisabled-> bu da sütun adıyla ters boolean. ya 0 ya da nan yazmışlar ama dikkat edelim

Census_ThresholdOptIn-> bunu boolean gibi 0 1 içeriyor ama desktoplar için batarya yok yani nan yazmışlar. 

Census_IsWIMBootEnabled-> bu da ya 0 ya nan yazıyor.

Census_Is*-> bunlarda nan yok gözüme çarpan, hepsi nizami boolean
Wdft_IsGamer-> bu da boolean ama birkaç tane nan var, Wdft_RegionIdentifier-> bu da normal float dtype ama nan var

HasDetections-> TARGET. nan yok tabii ki



birkaç eksik daha var

Census_OEMModelIdentifier, Census_OEMNameIdentifier sütunları %1 eksik. Census_ProcessorCoreCount ve Census_ProcessorManufacturerIdentifier %0.5 kadar eksik (ikisi de aynı sayıda eksik). Census_ProcessorModelIdentifier da öncesi census processor sütunlarından 1 fazla kadar eksik. Census_PrimaryDiskTypeName sütununda na olmayan UNKNOWN işaretçisi de var ama aynı zamanda na da koymuşlar. Census_ChassisTypeName 6 tane eksik var bu da baya garip. Census_InternalPrimaryDiagonalDisplaySizeInInches Census_InternalPrimaryDisplayResolutionHorizontal Census_InternalPrimaryDisplayResolutionVertical

bunlar da birbirleriyle neredeyse aynı sayıda  +- 1 kadar farkla eksik.  Census_OSInstallLanguageIdentifier bunda 680 kadar eksik var. Census_FirmwareManufacturerIdentifier ve Census_FirmwareVersionIdentifier %2 eksik. Census_IsVirtualDevice boolean normalde ama 185 tane eksiği var. Census_IsAlwaysOnAlwaysConnectedCapable %1 den biraz az eksik var

In [11]:
df = df.drop(columns=['PuaMode', 'Census_ProcessorClass', "DefaultBrowsersIdentifier"])
print("PuaMode, Census_ProcessorClass, DefaultBrowsersIdentifier drop edildi çünkü yüksek null.")

df["AVProductsInstalled"] = df["AVProductsInstalled"].fillna(-1)
df["AVProductsEnabled"] = df["AVProductsEnabled"].fillna(-1)
df["AVProductStatesIdentifier"] = df["AVProductStatesIdentifier"].fillna(-1)
df["RtpStateBitfield"] = df["RtpStateBitfield"].fillna(-1) 
df["CityIdentifier"] = df["CityIdentifier"].fillna(-1)
df["GeoNameIdentifier"] = df["GeoNameIdentifier"].fillna(-1) 
df["OsBuildLab"] = df["OsBuildLab"].fillna('-1') 

bool_cols = [
    'Census_HasOpticalDiskDrive', 'Firewall', 'SMode', 'IsProtected', 
    'AutoSampleOptIn', 'IsSxsPassiveMode', 'IsBeta', 'Census_IsSecureBootEnabled',
    'Census_IsFlightingInternal', 'Census_IsFlightsDisabled', 'Census_ThresholdOptIn', 
    'Census_IsWIMBootEnabled', 'Wdft_IsGamer', 'Census_IsVirtualDevice', 
    'Census_IsAlwaysOnAlwaysConnectedCapable' 
]
df[bool_cols] = df[bool_cols].fillna(0) 
id_hardware_cols_fix = [
    'Census_OEMModelIdentifier', 'Census_OEMNameIdentifier', 'Census_ProcessorModelIdentifier', 
    'Census_ProcessorManufacturerIdentifier', 'Census_FirmwareManufacturerIdentifier', 
    'Census_FirmwareVersionIdentifier', 'Census_OSInstallLanguageIdentifier',
    'Census_ProcessorCoreCount', 'Census_InternalPrimaryDiagonalDisplaySizeInInches', 
    'Census_InternalPrimaryDisplayResolutionHorizontal', 'Census_InternalPrimaryDisplayResolutionVertical',
    'UacLuaenable', 'Wdft_RegionIdentifier'
]
df[id_hardware_cols_fix] = df[id_hardware_cols_fix].fillna(-1)


df['Census_InternalBatteryType'] = df['Census_InternalBatteryType'].fillna('Unknown') 
df["SmartScreen"] = df["SmartScreen"].fillna('Unknown') 
df["OrganizationIdentifier"] = df["OrganizationIdentifier"].fillna(-1) 
df['Census_ChassisTypeName'] = df['Census_ChassisTypeName'].fillna('Unknown')

df['Census_TotalPhysicalRAM'] = df['Census_TotalPhysicalRAM'].fillna(1024)
df['Census_PrimaryDiskTotalCapacity'] = df['Census_PrimaryDiskTotalCapacity'].fillna(1024*10) 
df['Census_SystemVolumeTotalCapacity'] = df['Census_SystemVolumeTotalCapacity'].fillna(1024*10)

df['Census_PrimaryDiskTotalCapacity'] = da.log2(df['Census_PrimaryDiskTotalCapacity'] + 1).astype('float32')
df['Census_SystemVolumeTotalCapacity'] = da.log2(df['Census_SystemVolumeTotalCapacity'] + 1).astype('float32')
df['Census_TotalPhysicalRAM'] = da.log2(df['Census_TotalPhysicalRAM'] + 1).astype('float32')

PuaMode, Census_ProcessorClass, DefaultBrowsersIdentifier drop edildi çünkü yüksek null.

In [12]:
df_sample = df_sample.drop(columns=['PuaMode', 'Census_ProcessorClass', "DefaultBrowsersIdentifier"])
print("PuaMode, Census_ProcessorClass, DefaultBrowsersIdentifier drop edildi çünkü yüksek null.")

bool_cols = [
    'Census_HasOpticalDiskDrive', 
    'Firewall', 
    'SMode', 
    'IsProtected', 
    'AutoSampleOptIn', 
    'IsSxsPassiveMode', 
    'IsBeta', 
    'Census_IsSecureBootEnabled',
    'Census_IsFlightingInternal',
    'Census_IsFlightsDisabled', 
    'Census_ThresholdOptIn',     
    'Census_IsWIMBootEnabled',   
    'Wdft_IsGamer'            
]

df_sample[bool_cols] = df_sample[bool_cols].fillna(-1)

id_cols_fix = [
    'Census_OEMModelIdentifier', 
    'Census_OEMNameIdentifier', 
    'Census_ProcessorModelIdentifier', 
    'Census_ProcessorManufacturerIdentifier', 
    'Census_FirmwareManufacturerIdentifier', 
    'Census_FirmwareVersionIdentifier', 
    'Census_OSInstallLanguageIdentifier' 
]
df_sample[id_cols_fix] = df_sample[id_cols_fix].fillna(-1)

hardware_cols = [
    'Census_ProcessorCoreCount', 
    'Census_InternalPrimaryDiagonalDisplaySizeInInches', 
    'Census_InternalPrimaryDisplayResolutionHorizontal', 
    'Census_InternalPrimaryDisplayResolutionVertical'
]
df_sample[hardware_cols] = df_sample[hardware_cols].fillna(-1)

df_sample['Census_PrimaryDiskTypeName'] = df_sample['Census_PrimaryDiskTypeName'].fillna('UNKNOWN')
df_sample['Census_PrimaryDiskTypeName'] = df_sample['Census_PrimaryDiskTypeName'].str.upper()

df_sample['Census_ChassisTypeName'] = df_sample['Census_ChassisTypeName'].fillna('Unknown')

df_sample['Census_IsVirtualDevice'] = df_sample['Census_IsVirtualDevice'].fillna(0)
df_sample['Census_IsAlwaysOnAlwaysConnectedCapable'] = df_sample['Census_IsAlwaysOnAlwaysConnectedCapable'].fillna(0)

df_sample["AVProductsInstalled"] = df_sample["AVProductsInstalled"].fillna(-1)
df_sample["AVProductsEnabled"] = df_sample["AVProductsEnabled"].fillna(-1)
df_sample["AVProductStatesIdentifier"] = df_sample["AVProductStatesIdentifier"].fillna(-1)

df_sample["RtpStateBitfield"] = df_sample["RtpStateBitfield"].fillna(df_sample["RtpStateBitfield"].mode())
df_sample["CityIdentifier"] = df_sample["CityIdentifier"].fillna(df_sample["CityIdentifier"].mode())
df_sample["GeoNameIdentifier"] = df_sample["GeoNameIdentifier"].fillna(df_sample["GeoNameIdentifier"].mode())
df_sample["OsBuildLab"] = df_sample["OsBuildLab"].fillna(df_sample["OsBuildLab"].mode())

df_sample['Census_InternalBatteryNumberOfCharges'] = df_sample['Census_InternalBatteryNumberOfCharges'].fillna(-1)
df_sample['Census_InternalBatteryType'] = df_sample['Census_InternalBatteryType'].fillna(-1)
df_sample["SmartScreen"] = df_sample["SmartScreen"].fillna(-1)
df_sample["OrganizationIdentifier"] = df_sample["OrganizationIdentifier"].fillna(-1)
print("batarya ve SmartScreen sütunları null değerler -1 ile dolduruldu.")

df_sample['Wdft_RegionIdentifier'] = df_sample['Wdft_RegionIdentifier'].fillna(-1)
df_sample['Wdft_IsGamer'] = df_sample['Wdft_IsGamer'].fillna(-1)

df_sample['Census_TotalPhysicalRAM'] = df_sample['Census_TotalPhysicalRAM'].fillna(1024)
df_sample['Census_PrimaryDiskTotalCapacity'] = df_sample['Census_PrimaryDiskTotalCapacity'].fillna(1024*10) 
df_sample['Census_SystemVolumeTotalCapacity'] = df_sample['Census_SystemVolumeTotalCapacity'].fillna(1024*10)
df_sample['Census_PrimaryDiskTotalCapacity'] = da.log2(df_sample['Census_PrimaryDiskTotalCapacity'] + 1)
df_sample['Census_SystemVolumeTotalCapacity'] = da.log2(df_sample['Census_SystemVolumeTotalCapacity'] + 1)
df_sample['Census_TotalPhysicalRAM'] = da.log2(df_sample['Census_TotalPhysicalRAM'] + 1).astype('float32')
df_sample['UacLuaenable'] = df_sample['UacLuaenable'].fillna(-1).astype('float32')
df_sample['Wdft_RegionIdentifier'] = df_sample['Wdft_RegionIdentifier'].fillna(-1)

print("tüm işlemler bitti")

PuaMode, Census_ProcessorClass, DefaultBrowsersIdentifier drop edildi çünkü yüksek null.
batarya ve SmartScreen sütunları null değerler -1 ile dolduruldu.
tüm işlemler bitti

In [13]:
df_sample

,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,AVProductStatesIdentifier,AVProductsInstalled,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0000028988387b115f69f31a3bf04f09,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1735.0,0.0,7.0,0.0,53447.0,1.0,...,36144.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,10.0,0
1,000007535c3f730efa9ea0b7ef1bd645,win8defender,1.1.14600.4,4.13.17134.1,1.263.48.0,0.0,7.0,0.0,53447.0,1.0,...,57858.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,8.0,0
2,000007905a28d863f6d0d597892cd692,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1341.0,0.0,7.0,0.0,53447.0,1.0,...,52682.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,3.0,0
3,00000b11598a75ea8ba1beea8459149f,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1527.0,0.0,7.0,0.0,53447.0,1.0,...,20050.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,3.0,1
4,000014a5f00daa18e76b81417eeb99fc,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1379.0,0.0,7.0,0.0,53447.0,1.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,02e11f9b051950ba19ef87553f24b3d2,win8defender,1.1.15200.1,4.8.10240.17443,1.275.193.0,0.0,7.0,0.0,42086.0,2.0,...,12456.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0
99996,02e11ff750f98912e9073afe15bf5018,win8defender,1.1.15100.1,4.18.1806.18062,1.273.371.0,0.0,7.0,0.0,53447.0,1.0,...,43238.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,11.0,1
99997,02e120fd73a9b3981b80a879f1d94729,win8defender,1.1.15200.1,4.18.1807.18075,1.275.1244.0,0.0,7.0,0.0,7945.0,2.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0
99998,02e123408acf92064932e0900a42667b,win8defender,1.1.15200.1,4.18.1807.18075,1.275.1362.0,0.0,7.0,0.0,53447.0,1.0,...,52295.0,1.0,-1.0,0.0,0.0,0.0,0.0,-1.0,-1.0,0
99999,02e125f54e5e4aefc7a42cae452fe9b2,win8defender,1.1.15200.1,4.10.14393.1613,1.275.46.0,0.0,7.0,0.0,53447.0,1.0,...,31835.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0

In [14]:
for col in list(df_sample.columns):
  print(col, ":", df_sample[col].nunique())

MachineIdentifier : 100000
ProductName : 2
EngineVersion : 42
AppVersion : 80
AvSigVersion : 4027
IsBeta : 1
RtpStateBitfield : 6
IsSxsPassiveMode : 2
AVProductStatesIdentifier : 2070
AVProductsInstalled : 6
AVProductsEnabled : 6
HasTpm : 2
CountryIdentifier : 221
CityIdentifier : 15812
OrganizationIdentifier : 38
GeoNameIdentifier : 242
LocaleEnglishNameIdentifier : 186
Platform : 4
Processor : 3
OsVer : 11
OsBuild : 43
OsSuite : 7
OsPlatformSubRelease : 9
OsBuildLab : 369
SkuEdition : 8
IsProtected : 3
AutoSampleOptIn : 2
SMode : 3
IeVerIdentifier : 151
SmartScreen : 12
Firewall : 3
UacLuaenable : 4
Census_MDC2FormFactor : 12
Census_DeviceFamily : 2
Census_OEMNameIdentifier : 861
Census_OEMModelIdentifier : 16266
Census_ProcessorCoreCount : 18
Census_ProcessorManufacturerIdentifier : 5
Census_ProcessorModelIdentifier : 1739
Census_PrimaryDiskTotalCapacity : 480
Census_PrimaryDiskTypeName : 4
Census_SystemVolumeTotalCapacity : 45227
Census_HasOpticalDiskDrive : 2
Census_TotalPhysicalRAM : 172
Census_ChassisTypeName : 30
Census_InternalPrimaryDiagonalDisplaySizeInInches : 370
Census_InternalPrimaryDisplayResolutionHorizontal : 170
Census_InternalPrimaryDisplayResolutionVertical : 197
Census_PowerPlatformRoleName : 9
Census_InternalBatteryType : 23
Census_InternalBatteryNumberOfCharges : 1791
Census_OSVersion : 260
Census_OSArchitecture : 3
Census_OSBranch : 15
Census_OSBuildNumber : 38
Census_OSBuildRevision : 219
Census_OSEdition : 19
Census_OSSkuName : 17
Census_OSInstallTypeName : 9
Census_OSInstallLanguageIdentifier : 40
Census_OSUILocaleIdentifier : 63
Census_OSWUAutoUpdateOptionsName : 6
Census_IsPortableOperatingSystem : 2
Census_GenuineStateName : 4
Census_ActivationChannel : 6
Census_IsFlightingInternal : 2
Census_IsFlightsDisabled : 2
Census_FlightRing : 7
Census_ThresholdOptIn : 3
Census_FirmwareManufacturerIdentifier : 173
Census_FirmwareVersionIdentifier : 12457
Census_IsSecureBootEnabled : 2
Census_IsWIMBootEnabled : 2
Census_IsVirtualDevice : 2
Census_IsTouchEnabled : 2
Census_IsPenCapable : 2
Census_IsAlwaysOnAlwaysConnectedCapable : 2
Wdft_IsGamer : 3
Wdft_RegionIdentifier : 16
HasDetections : 2

In [15]:
df_sample

,MachineIdentifier,ProductName,EngineVersion,AppVersion,AvSigVersion,IsBeta,RtpStateBitfield,IsSxsPassiveMode,AVProductStatesIdentifier,AVProductsInstalled,...,Census_FirmwareVersionIdentifier,Census_IsSecureBootEnabled,Census_IsWIMBootEnabled,Census_IsVirtualDevice,Census_IsTouchEnabled,Census_IsPenCapable,Census_IsAlwaysOnAlwaysConnectedCapable,Wdft_IsGamer,Wdft_RegionIdentifier,HasDetections
0,0000028988387b115f69f31a3bf04f09,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1735.0,0.0,7.0,0.0,53447.0,1.0,...,36144.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,10.0,0
1,000007535c3f730efa9ea0b7ef1bd645,win8defender,1.1.14600.4,4.13.17134.1,1.263.48.0,0.0,7.0,0.0,53447.0,1.0,...,57858.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,8.0,0
2,000007905a28d863f6d0d597892cd692,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1341.0,0.0,7.0,0.0,53447.0,1.0,...,52682.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,3.0,0
3,00000b11598a75ea8ba1beea8459149f,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1527.0,0.0,7.0,0.0,53447.0,1.0,...,20050.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,3.0,1
4,000014a5f00daa18e76b81417eeb99fc,win8defender,1.1.15100.1,4.18.1807.18075,1.273.1379.0,0.0,7.0,0.0,53447.0,1.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,02e11f9b051950ba19ef87553f24b3d2,win8defender,1.1.15200.1,4.8.10240.17443,1.275.193.0,0.0,7.0,0.0,42086.0,2.0,...,12456.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0
99996,02e11ff750f98912e9073afe15bf5018,win8defender,1.1.15100.1,4.18.1806.18062,1.273.371.0,0.0,7.0,0.0,53447.0,1.0,...,43238.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,11.0,1
99997,02e120fd73a9b3981b80a879f1d94729,win8defender,1.1.15200.1,4.18.1807.18075,1.275.1244.0,0.0,7.0,0.0,7945.0,2.0,...,19844.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0
99998,02e123408acf92064932e0900a42667b,win8defender,1.1.15200.1,4.18.1807.18075,1.275.1362.0,0.0,7.0,0.0,53447.0,1.0,...,52295.0,1.0,-1.0,0.0,0.0,0.0,0.0,-1.0,-1.0,0
99999,02e125f54e5e4aefc7a42cae452fe9b2,win8defender,1.1.15200.1,4.10.14393.1613,1.275.46.0,0.0,7.0,0.0,53447.0,1.0,...,31835.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0

In [16]:
bool_like_cols = [
    'Census_HasOpticalDiskDrive', 'Firewall', 'SMode', 'IsProtected', 
    'AutoSampleOptIn', 'IsSxsPassiveMode', 'IsBeta', 'Census_IsSecureBootEnabled',
    'Census_IsFlightingInternal', 'Census_IsFlightsDisabled', 'Census_ThresholdOptIn', 
    'Census_IsWIMBootEnabled', 'Wdft_IsGamer', 'Census_IsVirtualDevice', 
    'Census_IsAlwaysOnAlwaysConnectedCapable', 'HasTpm', 'Census_IsTouchEnabled', 
    'Census_IsPenCapable'
]
df[bool_like_cols] = df[bool_like_cols].astype('int8')
del df_sample

In [17]:
def get_freq_map(ddf, feat):
    counts = ddf[feat].value_counts().compute()
    total_count = len(ddf)

    freq_map = (counts/total_count).to_dict()
    return freq_map

In [18]:
df_train_dask, df_test_dask, df_val_dask = df.random_split([0.75, 0.20, 0.05], random_state=42) 
hc_cols_to_encode = [
    'CityIdentifier', 
    'Census_OEMModelIdentifier', 
    'Census_FirmwareVersionIdentifier', 
    'AvSigVersion',
    'AVProductStatesIdentifier',
    'AppVersion', 
    'Census_OSVersion', 
    'EngineVersion', 
    'OsBuildLab'
]

print("Frequency Encoding başladı...")

Frequency Encoding başladı...

In [19]:
from tqdm import tqdm
all_counts = {}
for col in tqdm(hc_cols_to_encode):
    all_counts[col] = df_train_dask[col].value_counts()


print("\n9 Sütun Hesaplanıyor")
all_counts_result = dd.compute(all_counts)[0]
all_freq_maps = {}
total_count = len(df_train_dask)
for col in hc_cols_to_encode:
    counts = all_counts_result[col]
    freq_map = (counts / total_count).to_dict()
    all_freq_maps[col] = freq_map

print("\nFrequency Encoding yapıldı")

100%|██████████| 9/9 [00:00<00:00, 718.19it/s]

9 Sütun Hesaplanıyor

Frequency Encoding yapıldı

In [20]:
print("Frequency Encoding Uygulaması Başladı")

for col in tqdm(hc_cols_to_encode):
    freq_map = all_freq_maps[col]

    df_train_dask = df_train_dask.assign(**{f'{col}_FreqEnc': df_train_dask[col].map_partitions(
        lambda x: x.map(freq_map).fillna(0.0).astype("float32"), meta=('float32')
    )})
    
    df_val_dask = df_val_dask.assign(**{f'{col}_FreqEnc': df_val_dask[col].map_partitions(
        lambda x: x.map(freq_map).fillna(0.0).astype("float32"), meta=('float32')
    )})

    df_test_dask = df_test_dask.assign(**{f'{col}_FreqEnc': df_test_dask[col].map_partitions(
        lambda x: x.map(freq_map).fillna(0.0).astype("float32"), meta=('float32')
    )})
    
    df_train_dask = df_train_dask.drop(columns=[col])
    df_test_dask = df_test_dask.drop(columns=[col])
    df_val_dask = df_val_dask.drop(columns=[col])

print("\nFrequency Encoding tamamlandı")

Frequency Encoding Uygulaması Başladı

  0%|          | 0/9 [00:00<?, ?it/s]/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
 11%|█         | 1/9 [00:00<00:00,  9.81it/s]/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
 22%|██▏       | 2/9 [00:00<00:00,  7.99it/s]/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
 56%|█████▌    | 5/9 [00:00<00:00, 15.45it/s]/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
100%|██████████| 9/9 [00:00<00:00, 20.30it/s]

Frequency Encoding tamamlandı

In [21]:
df_train_dask

Dask DataFrame Structure:
               MachineIdentifier ProductName IsBeta RtpStateBitfield IsSxsPassiveMode AVProductsInstalled AVProductsEnabled HasTpm CountryIdentifier OrganizationIdentifier GeoNameIdentifier LocaleEnglishNameIdentifier Platform Processor   OsVer  OsBuild  OsSuite OsPlatformSubRelease SkuEdition IsProtected AutoSampleOptIn SMode IeVerIdentifier SmartScreen Firewall UacLuaenable Census_MDC2FormFactor Census_DeviceFamily Census_OEMNameIdentifier Census_ProcessorCoreCount Census_ProcessorManufacturerIdentifier Census_ProcessorModelIdentifier Census_PrimaryDiskTotalCapacity Census_PrimaryDiskTypeName Census_SystemVolumeTotalCapacity Census_HasOpticalDiskDrive Census_TotalPhysicalRAM Census_ChassisTypeName Census_InternalPrimaryDiagonalDisplaySizeInInches Census_InternalPrimaryDisplayResolutionHorizontal Census_InternalPrimaryDisplayResolutionVertical Census_PowerPlatformRoleName Census_InternalBatteryType Census_InternalBatteryNumberOfCharges Census_OSArchitecture Census_OSBranch Census_OSBuildNumber Census_OSBuildRevision Census_OSEdition Census_OSSkuName Census_OSInstallTypeName Census_OSInstallLanguageIdentifier Census_OSUILocaleIdentifier Census_OSWUAutoUpdateOptionsName Census_IsPortableOperatingSystem Census_GenuineStateName Census_ActivationChannel Census_IsFlightingInternal Census_IsFlightsDisabled Census_FlightRing Census_ThresholdOptIn Census_FirmwareManufacturerIdentifier Census_IsSecureBootEnabled Census_IsWIMBootEnabled Census_IsVirtualDevice Census_IsTouchEnabled Census_IsPenCapable Census_IsAlwaysOnAlwaysConnectedCapable Wdft_IsGamer Wdft_RegionIdentifier HasDetections CityIdentifier_FreqEnc Census_OEMModelIdentifier_FreqEnc Census_FirmwareVersionIdentifier_FreqEnc AvSigVersion_FreqEnc AVProductStatesIdentifier_FreqEnc AppVersion_FreqEnc Census_OSVersion_FreqEnc EngineVersion_FreqEnc OsBuildLab_FreqEnc
npartitions=68
                          string      string   int8          float32             int8             float32           float32   int8           float32                float32           float32                     float32   string    string  string  float32  float32               string     string        int8            int8  int8         float32      string     int8      float32                string              string                  float32                   float32                                float32                         float32                         float32                     string                          float32                       int8                 float32                 string                                           float32                                           float32                                         float32                       string                     string                               float32                string          string              float32                float32           string           string                   string                            float32                     float32                           string                          float32                  string                   string                       int8                     int8            string                  int8                               float32                       int8                    int8                   int8                  int8                int8                                    int8         int8               float32         uint8                float32                           float32                                  float32              float32                           float32            float32                  float32               float32            float32
                             ...         ...    ...              ...              ...                 ...               ...    ...               ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...         ...             ...   ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                                    ...                             ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...                    ...                               ...                                      ...                  ...                               ...                ...                      ...                   ...                ...
...                          ...         ...    ...              ...              ...                 ...               ...    ...               ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...         ...             ...   ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                                    ...                             ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...                    ...                               ...                                      ...                  ...                               ...                ...                      ...                   ...                ...
                             ...         ...    ...              ...              ...                 ...               ...    ...               ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...         ...             ...   ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                                    ...                             ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...                    ...                               ...                                      ...                  ...                               ...                ...                      ...                   ...                ...
                             ...         ...    ...              ...              ...                 ...               ...    ...               ...                    ...               ...                         ...      ...       ...     ...      ...      ...                  ...        ...         ...             ...   ...             ...         ...      ...          ...                   ...                 ...                      ...                       ...                                    ...                             ...                             ...                        ...                              ...                        ...                     ...                    ...                                               ...                                               ...                                             ...                          ...                        ...                                   ...                   ...             ...                  ...                    ...              ...              ...                      ...                                ...                         ...                              ...                              ...                     ...                      ...                        ...                      ...               ...                   ...                                   ...                        ...                     ...                    ...                   ...                 ...                                     ...          ...                   ...           ...                    ...                               ...                                      ...                  ...                               ...                ...                      ...                   ...                ...
Dask Name: drop_by_shallow_copy, 153 expressions
Expr=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=Drop(frame=Assign(frame=SplitTake(frame=Split(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Assign(frame=Drop(frame=ArrowStringConversion(frame=FromMapProjectable(755b8a7)), columns=['PuaMode', 'Census_ProcessorClass', 'DefaultBrowsersIdentifier']))))))))))))))))))))), frac=[0.75, 0.2, 0.05], random_state=42, shuffle=False), i=0, ndim=2)), columns=['CityIdentifier'])), columns=['Census_OEMModelIdentifier'])), columns=['Census_FirmwareVersionIdentifier'])), columns=['AvSigVersion'])), columns=['AVProductStatesIdentifier'])), columns=['AppVersion'])), columns=['Census_OSVersion'])), columns=['EngineVersion'])), columns=['OsBuildLab'])

In [22]:
df_train_dask = df_train_dask.drop("MachineIdentifier", axis=1)
df_test_dask = df_test_dask.drop("MachineIdentifier", axis=1)
df_val_dask = df_val_dask.drop("MachineIdentifier", axis=1)

In [23]:
for col in df_train_dask.select_dtypes("object"):
    categories = df_train_dask[col].nunique().compute()

    def map_codes(ddf):
        ddf[col] = ddf[col].astype("category")
        ddf[col] = ddf[col].cat.set_categories(categories, ordered=False)
        ddf[col] = ddf[col].cat.codes.replace(-1, 0).astype('int16') 
        return ddf
    df_train_dask = df_train_dask.map_partitions(map_codes, meta=df_train_dask._meta)
    df_val_dask = df_val_dask.map_partitions(map_codes, meta=df_val_dask._meta)
    df_test_dask = df_test_dask.map_partitions(map_codes, meta=df_test_dask._meta)
    print(f"  -> {col} Label Encoded planlandı.")

In [24]:
import lightgbm as lgb 
float32_cols = [col for col, dtype in df_train_dask.dtypes.items() if str(dtype) == 'float32']

print(f"Toplam float32 sütun sayısı: {len(float32_cols)}")

for col in float32_cols:
    df_train_dask[col] = df_train_dask[col].astype('float16')
    df_val_dask[col] = df_val_dask[col].astype('float16')
    df_test_dask[col] = df_test_dask[col].astype('float16')

X_train = df_train_dask.compute()
y_train = df_train_dask['HasDetections'].compute()

X_val = df_val_dask.compute()
y_val = df_val_dask['HasDetections'].compute()

Toplam float32 sütun sayısı: 38

/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/home/tunahan/miniconda3/envs/ml_env/lib/python3.11/site-packages/dask/dataframe/dask_expr/_expr.py:4136: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(

In [ ]:
params = {
    "objective": "binary",
    "metric": "auc",
    "n_estimators":5000,
    "learning_rate": 2e-2,
    "num_leaves": 32,
    "colsample_bytree":0.7,
    "random_state":42,
    "n_jobs":-1,
    "verbose":-1,
    "subsample":0.7
}
for df in [X_train, X_val]:
    for col in df.select_dtypes("string"):
        df[col] = df[col].astype("object")

ValueError: pandas dtypes must be int, float or bool.
Fields with bad pandas dtypes: ProductName: object, Platform: object, Processor: object, OsVer: object, OsPlatformSubRelease: object, SkuEdition: object, SmartScreen: object, Census_MDC2FormFactor: object, Census_DeviceFamily: object, Census_PrimaryDiskTypeName: object, Census_ChassisTypeName: object, Census_PowerPlatformRoleName: object, Census_InternalBatteryType: object, Census_OSArchitecture: object, Census_OSBranch: object, Census_OSEdition: object, Census_OSSkuName: object, Census_OSInstallTypeName: object, Census_OSWUAutoUpdateOptionsName: object, Census_GenuineStateName: object, Census_ActivationChannel: object, Census_FlightRing: object

In [ ]:
for df in [X_train, X_val]:
    for col in df.select_dtypes("object"):
        df[col] = 1
lgb_clf = lgb.LGBMClassifier(**params)

In [ ]:
lgb_clf.fit(X_train, y_train,
            eval_set=[(X_val, y_val)],
            eval_metric="auc",
            callbacks=[lgb.early_stopping(stopping_rounds=100, verbose=100)])

In [26]:
X_train.dtypes

ProductName                           object
IsBeta                                  int8
RtpStateBitfield                     float16
IsSxsPassiveMode                        int8
AVProductsInstalled                  float16
                                      ...
AVProductStatesIdentifier_FreqEnc    float16
AppVersion_FreqEnc                   float16
Census_OSVersion_FreqEnc             float16
EngineVersion_FreqEnc                float16
OsBuildLab_FreqEnc                   float16
Length: 79, dtype: object

In [ ]:
lgb_clf.fit(X_train, y_train,
            eval_set=[(X_val, y_val)],
            eval_metric="auc",
            callbacks=[lgb.early_stopping(stopping_rounds=100, verbose=100)])

In [ ]:
del X_train, y_train, X_val, y_val
X_test = df_test_dask.compute()
y_test = df_test_dask["HasDetections"]
for col in X_test.select_dtypes("string"):
    X_test[col] = X_test[col].astype("object")
from sklearn.metrics import roc_auc_score
y_test_pred_proba = lgb_clf.predict_proba(X_test)[:, 1]
final_auc_score = roc_auc_score(y_test, y_test_pred_proba)

print(f"\nModel Eğitimi ve Final Değerlendirme Tamamlandı!")
print(f"Validation AUC Skoru: {lgb_clf.best_score_['valid_0']['auc']:.5f}")
print(f"Test AUC (Nihai Raporlama) Skoru: {final_auc_score:.5f}")